AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  nimo-crypto-api

Globals:
  Function:
    Timeout: 10
    Runtime: nodejs22.x

Resources:
  GetCryptoPriceFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: GetCryptoPriceFunction
      CodeUri: getCryptoPriceAndSendEmail/
      Handler: app.handler
      Events:
        CryptoPriceApi:
          Type: Api
          Properties:
            Path: /crypto/price
            Method: post
      Policies:
        - AmazonSESFullAccess
        - DynamoDBCrudPolicy:
            TableName: crypto_search_history
  CryptoSearchHistoryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: crypto_search_history
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH

Outputs:
  GetCryptoPriceFunctionApi:
    Description: "API Gateway endpoint URL for GetCryptoPriceFunction"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/crypto/price"
  GetCryptoPriceFunction:
    Description: "GetCryptoPriceFunction ARN"
    Value: !GetAtt GetCryptoPriceFunction.Arn
